apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: git-parser-ingress
  namespace: git-parser
spec:
  rules:
  - host: git-parser.seredavin.ru
    servicePort:
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: ui-service
            port: 
              number: 80