apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: git-parser-ingress
  namespace: git-parser
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: git-parser.seredavin.ru
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui-service
                port:
                  number: 80