apiVersion: networking.k8s.io/v1beta
kind: Ingress
metadata:
  name: git-parser-ingress
  namespace: git-parser
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ui-service
                port:
                  number: 80